// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (owner_id, business_type, name, city_plot_id)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, business_type, name, city_plot_id, status, opened_at, inventory, production_config
`

type CreateBusinessParams struct {
	OwnerID      uuid.UUID   `json:"owner_id"`
	BusinessType string      `json:"business_type"`
	Name         string      `json:"name"`
	CityPlotID   pgtype.UUID `json:"city_plot_id"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.OwnerID,
		arg.BusinessType,
		arg.Name,
		arg.CityPlotID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BusinessType,
		&i.Name,
		&i.CityPlotID,
		&i.Status,
		&i.OpenedAt,
		&i.Inventory,
		&i.ProductionConfig,
	)
	return i, err
}

const createEmployment = `-- name: CreateEmployment :one
INSERT INTO employment (business_id, employee_id, wage_rate, min_daily_hours)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, employee_id, wage_rate, min_daily_hours, started_at, status
`

type CreateEmploymentParams struct {
	BusinessID    uuid.UUID      `json:"business_id"`
	EmployeeID    uuid.UUID      `json:"employee_id"`
	WageRate      pgtype.Numeric `json:"wage_rate"`
	MinDailyHours pgtype.Numeric `json:"min_daily_hours"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) (Employment, error) {
	row := q.db.QueryRow(ctx, createEmployment,
		arg.BusinessID,
		arg.EmployeeID,
		arg.WageRate,
		arg.MinDailyHours,
	)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EmployeeID,
		&i.WageRate,
		&i.MinDailyHours,
		&i.StartedAt,
		&i.Status,
	)
	return i, err
}

const getBusinessesByOwner = `-- name: GetBusinessesByOwner :many
SELECT id, owner_id, business_type, name, city_plot_id, status, opened_at, inventory, production_config FROM businesses
WHERE owner_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) GetBusinessesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinessesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BusinessType,
			&i.Name,
			&i.CityPlotID,
			&i.Status,
			&i.OpenedAt,
			&i.Inventory,
			&i.ProductionConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyLaborByDay = `-- name: GetDailyLaborByDay :many
SELECT id, player_id, business_id, economic_day, hours_worked, created_at, updated_at FROM daily_labor
WHERE economic_day = $1
`

func (q *Queries) GetDailyLaborByDay(ctx context.Context, economicDay int32) ([]DailyLabor, error) {
	rows, err := q.db.Query(ctx, getDailyLaborByDay, economicDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLabor{}
	for rows.Next() {
		var i DailyLabor
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.BusinessID,
			&i.EconomicDay,
			&i.HoursWorked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminateEmployment = `-- name: TerminateEmployment :exec
UPDATE employment SET status = 'TERMINATED'
WHERE id = $1
`

func (q *Queries) TerminateEmployment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, terminateEmployment, id)
	return err
}

const updateInventory = `-- name: UpdateInventory :exec
UPDATE businesses SET inventory = $1
WHERE id = $2
`

type UpdateInventoryParams struct {
	Inventory []byte    `json:"inventory"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error {
	_, err := q.db.Exec(ctx, updateInventory, arg.Inventory, arg.ID)
	return err
}

const updateProductionConfig = `-- name: UpdateProductionConfig :exec
UPDATE businesses SET production_config = $1
WHERE id = $2
`

type UpdateProductionConfigParams struct {
	ProductionConfig []byte    `json:"production_config"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProductionConfig(ctx context.Context, arg UpdateProductionConfigParams) error {
	_, err := q.db.Exec(ctx, updateProductionConfig, arg.ProductionConfig, arg.ID)
	return err
}

const upsertDailyLabor = `-- name: UpsertDailyLabor :one
INSERT INTO daily_labor (player_id, business_id, economic_day, hours_worked)
VALUES ($1, $2, $3, $4)
ON CONFLICT (player_id, business_id, economic_day) 
DO UPDATE SET hours_worked = daily_labor.hours_worked + $4, updated_at = NOW()
RETURNING id, player_id, business_id, economic_day, hours_worked, created_at, updated_at
`

type UpsertDailyLaborParams struct {
	PlayerID    uuid.UUID      `json:"player_id"`
	BusinessID  uuid.UUID      `json:"business_id"`
	EconomicDay int32          `json:"economic_day"`
	HoursWorked pgtype.Numeric `json:"hours_worked"`
}

func (q *Queries) UpsertDailyLabor(ctx context.Context, arg UpsertDailyLaborParams) (DailyLabor, error) {
	row := q.db.QueryRow(ctx, upsertDailyLabor,
		arg.PlayerID,
		arg.BusinessID,
		arg.EconomicDay,
		arg.HoursWorked,
	)
	var i DailyLabor
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.BusinessID,
		&i.EconomicDay,
		&i.HoursWorked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
