// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (player_id, type)
VALUES ($1, $2)
RETURNING id, player_id, type, created_at
`

type CreateAccountParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Type     AccountType `json:"type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.PlayerID, arg.Type)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(CASE WHEN entry_type = 'CREDIT' THEN amount ELSE 0 END), 0) - 
       COALESCE(SUM(CASE WHEN entry_type = 'DEBIT' THEN amount ELSE 0 END), 0) AS balance
FROM transactions
WHERE account_id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const getAccountsByPlayer = `-- name: GetAccountsByPlayer :many
SELECT id, player_id, type, created_at FROM accounts
WHERE player_id = $1
`

func (q *Queries) GetAccountsByPlayer(ctx context.Context, playerID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionHistory = `-- name: GetTransactionHistory :many
SELECT id, account_id, amount, entry_type, transaction_type, reference_id, description, created_at FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionHistoryParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetTransactionHistory(ctx context.Context, arg GetTransactionHistoryParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionHistory, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.EntryType,
			&i.TransactionType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTreasuryAccount = `-- name: GetTreasuryAccount :one
SELECT id, player_id, type, created_at FROM accounts
WHERE type = 'TREASURY'
LIMIT 1
`

func (q *Queries) GetTreasuryAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getTreasuryAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const postTransaction = `-- name: PostTransaction :one
INSERT INTO transactions (account_id, amount, entry_type, transaction_type, reference_id, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, amount, entry_type, transaction_type, reference_id, description, created_at
`

type PostTransactionParams struct {
	AccountID       uuid.UUID       `json:"account_id"`
	Amount          pgtype.Numeric  `json:"amount"`
	EntryType       EntryType       `json:"entry_type"`
	TransactionType TransactionType `json:"transaction_type"`
	ReferenceID     pgtype.UUID     `json:"reference_id"`
	Description     pgtype.Text     `json:"description"`
}

func (q *Queries) PostTransaction(ctx context.Context, arg PostTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, postTransaction,
		arg.AccountID,
		arg.Amount,
		arg.EntryType,
		arg.TransactionType,
		arg.ReferenceID,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.EntryType,
		&i.TransactionType,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
