// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createListing = `-- name: CreateListing :one
INSERT INTO market_listings (seller_id, item_type, quantity, quantity_remaining, asking_price, escrow_account_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, seller_id, item_type, quantity, quantity_remaining, asking_price, escrow_account_id, status, created_at, updated_at
`

type CreateListingParams struct {
	SellerID          uuid.UUID      `json:"seller_id"`
	ItemType          string         `json:"item_type"`
	Quantity          int32          `json:"quantity"`
	QuantityRemaining int32          `json:"quantity_remaining"`
	AskingPrice       pgtype.Numeric `json:"asking_price"`
	EscrowAccountID   pgtype.UUID    `json:"escrow_account_id"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (MarketListing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.SellerID,
		arg.ItemType,
		arg.Quantity,
		arg.QuantityRemaining,
		arg.AskingPrice,
		arg.EscrowAccountID,
	)
	var i MarketListing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.ItemType,
		&i.Quantity,
		&i.QuantityRemaining,
		&i.AskingPrice,
		&i.EscrowAccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementListingQuantity = `-- name: DecrementListingQuantity :exec
UPDATE market_listings 
SET quantity_remaining = quantity_remaining - $1, updated_at = NOW()
WHERE id = $2 AND quantity_remaining >= $1
`

type DecrementListingQuantityParams struct {
	QuantityRemaining int32     `json:"quantity_remaining"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) DecrementListingQuantity(ctx context.Context, arg DecrementListingQuantityParams) error {
	_, err := q.db.Exec(ctx, decrementListingQuantity, arg.QuantityRemaining, arg.ID)
	return err
}

const getActiveListingsByItem = `-- name: GetActiveListingsByItem :many
SELECT id, seller_id, item_type, quantity, quantity_remaining, asking_price, escrow_account_id, status, created_at, updated_at FROM market_listings
WHERE item_type = $1 AND status = 'ACTIVE'
ORDER BY asking_price ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type GetActiveListingsByItemParams struct {
	ItemType string `json:"item_type"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetActiveListingsByItem(ctx context.Context, arg GetActiveListingsByItemParams) ([]MarketListing, error) {
	rows, err := q.db.Query(ctx, getActiveListingsByItem, arg.ItemType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketListing{}
	for rows.Next() {
		var i MarketListing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.ItemType,
			&i.Quantity,
			&i.QuantityRemaining,
			&i.AskingPrice,
			&i.EscrowAccountID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTradesByItem = `-- name: GetRecentTradesByItem :many
SELECT id, listing_id, buyer_id, seller_id, item_type, quantity, price_per_unit, traded_at FROM market_trades
WHERE item_type = $1
ORDER BY traded_at DESC
LIMIT $2
`

type GetRecentTradesByItemParams struct {
	ItemType string `json:"item_type"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) GetRecentTradesByItem(ctx context.Context, arg GetRecentTradesByItemParams) ([]MarketTrade, error) {
	rows, err := q.db.Query(ctx, getRecentTradesByItem, arg.ItemType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketTrade{}
	for rows.Next() {
		var i MarketTrade
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.ItemType,
			&i.Quantity,
			&i.PricePerUnit,
			&i.TradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTrade = `-- name: RecordTrade :one
INSERT INTO market_trades (listing_id, buyer_id, seller_id, item_type, quantity, price_per_unit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, listing_id, buyer_id, seller_id, item_type, quantity, price_per_unit, traded_at
`

type RecordTradeParams struct {
	ListingID    uuid.UUID      `json:"listing_id"`
	BuyerID      uuid.UUID      `json:"buyer_id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	ItemType     string         `json:"item_type"`
	Quantity     int32          `json:"quantity"`
	PricePerUnit pgtype.Numeric `json:"price_per_unit"`
}

func (q *Queries) RecordTrade(ctx context.Context, arg RecordTradeParams) (MarketTrade, error) {
	row := q.db.QueryRow(ctx, recordTrade,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.ItemType,
		arg.Quantity,
		arg.PricePerUnit,
	)
	var i MarketTrade
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.ItemType,
		&i.Quantity,
		&i.PricePerUnit,
		&i.TradedAt,
	)
	return i, err
}

const updateListingStatus = `-- name: UpdateListingStatus :exec
UPDATE market_listings SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateListingStatusParams struct {
	Status ListingStatus `json:"status"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) error {
	_, err := q.db.Exec(ctx, updateListingStatus, arg.Status, arg.ID)
	return err
}
