// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeWALLET   AccountType = "WALLET"
	AccountTypeBANK     AccountType = "BANK"
	AccountTypeESCROW   AccountType = "ESCROW"
	AccountTypeTREASURY AccountType = "TREASURY"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type BusinessStatus string

const (
	BusinessStatusACTIVE    BusinessStatus = "ACTIVE"
	BusinessStatusCLOSED    BusinessStatus = "CLOSED"
	BusinessStatusSUSPENDED BusinessStatus = "SUSPENDED"
)

func (e *BusinessStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessStatus(s)
	case string:
		*e = BusinessStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessStatus: %T", src)
	}
	return nil
}

type NullBusinessStatus struct {
	BusinessStatus BusinessStatus `json:"business_status"`
	Valid          bool           `json:"valid"` // Valid is true if BusinessStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessStatus), nil
}

type EmploymentStatus string

const (
	EmploymentStatusACTIVE     EmploymentStatus = "ACTIVE"
	EmploymentStatusTERMINATED EmploymentStatus = "TERMINATED"
)

func (e *EmploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmploymentStatus(s)
	case string:
		*e = EmploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EmploymentStatus: %T", src)
	}
	return nil
}

type NullEmploymentStatus struct {
	EmploymentStatus EmploymentStatus `json:"employment_status"`
	Valid            bool             `json:"valid"` // Valid is true if EmploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EmploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmploymentStatus), nil
}

type EntryType string

const (
	EntryTypeDEBIT  EntryType = "DEBIT"
	EntryTypeCREDIT EntryType = "CREDIT"
)

func (e *EntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryType(s)
	case string:
		*e = EntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryType: %T", src)
	}
	return nil
}

type NullEntryType struct {
	EntryType EntryType `json:"entry_type"`
	Valid     bool      `json:"valid"` // Valid is true if EntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryType), nil
}

type ListingStatus string

const (
	ListingStatusACTIVE    ListingStatus = "ACTIVE"
	ListingStatusSOLD      ListingStatus = "SOLD"
	ListingStatusEXPIRED   ListingStatus = "EXPIRED"
	ListingStatusCANCELLED ListingStatus = "CANCELLED"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus `json:"listing_status"`
	Valid         bool          `json:"valid"` // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusOPEN      ReviewStatus = "OPEN"
	ReviewStatusREVIEWED  ReviewStatus = "REVIEWED"
	ReviewStatusDISMISSED ReviewStatus = "DISMISSED"
	ReviewStatusACTIONED  ReviewStatus = "ACTIONED"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type TransactionType string

const (
	TransactionTypePLAYERTRANSFER  TransactionType = "PLAYER_TRANSFER"
	TransactionTypeWAGE            TransactionType = "WAGE"
	TransactionTypeTAX             TransactionType = "TAX"
	TransactionTypeMARKETSALE      TransactionType = "MARKET_SALE"
	TransactionTypeMARKETPURCHASE  TransactionType = "MARKET_PURCHASE"
	TransactionTypeESCROWLOCK      TransactionType = "ESCROW_LOCK"
	TransactionTypeESCROWRELEASE   TransactionType = "ESCROW_RELEASE"
	TransactionTypeBUSINESSREVENUE TransactionType = "BUSINESS_REVENUE"
	TransactionTypePROPERTYTAX     TransactionType = "PROPERTY_TAX"
	TransactionTypeINITIALGRANT    TransactionType = "INITIAL_GRANT"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	ID        uuid.UUID          `json:"id"`
	PlayerID  pgtype.UUID        `json:"player_id"`
	Type      AccountType        `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AdminAuditLog struct {
	ID             uuid.UUID          `json:"id"`
	AdminPlayerID  uuid.UUID          `json:"admin_player_id"`
	TargetPlayerID pgtype.UUID        `json:"target_player_id"`
	ActionType     string             `json:"action_type"`
	Parameters     []byte             `json:"parameters"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
}

type AnomalyFlag struct {
	ID                  uuid.UUID          `json:"id"`
	FlagType            string             `json:"flag_type"`
	ImplicatedPlayerIds []uuid.UUID        `json:"implicated_player_ids"`
	EvidenceSummary     pgtype.Text        `json:"evidence_summary"`
	DetectedAt          pgtype.Timestamptz `json:"detected_at"`
	ReviewStatus        ReviewStatus       `json:"review_status"`
}

type Business struct {
	ID               uuid.UUID          `json:"id"`
	OwnerID          uuid.UUID          `json:"owner_id"`
	BusinessType     string             `json:"business_type"`
	Name             string             `json:"name"`
	CityPlotID       pgtype.UUID        `json:"city_plot_id"`
	Status           BusinessStatus     `json:"status"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	Inventory        []byte             `json:"inventory"`
	ProductionConfig []byte             `json:"production_config"`
}

type DailyLabor struct {
	ID          uuid.UUID          `json:"id"`
	PlayerID    uuid.UUID          `json:"player_id"`
	BusinessID  uuid.UUID          `json:"business_id"`
	EconomicDay int32              `json:"economic_day"`
	HoursWorked pgtype.Numeric     `json:"hours_worked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EconomicSnapshot struct {
	ID          uuid.UUID          `json:"id"`
	EconomicDay int32              `json:"economic_day"`
	Metrics     []byte             `json:"metrics"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Employment struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	EmployeeID    uuid.UUID          `json:"employee_id"`
	WageRate      pgtype.Numeric     `json:"wage_rate"`
	MinDailyHours pgtype.Numeric     `json:"min_daily_hours"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	Status        EmploymentStatus   `json:"status"`
}

type MarketListing struct {
	ID                uuid.UUID          `json:"id"`
	SellerID          uuid.UUID          `json:"seller_id"`
	ItemType          string             `json:"item_type"`
	Quantity          int32              `json:"quantity"`
	QuantityRemaining int32              `json:"quantity_remaining"`
	AskingPrice       pgtype.Numeric     `json:"asking_price"`
	EscrowAccountID   pgtype.UUID        `json:"escrow_account_id"`
	Status            ListingStatus      `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type MarketTrade struct {
	ID           uuid.UUID          `json:"id"`
	ListingID    uuid.UUID          `json:"listing_id"`
	BuyerID      uuid.UUID          `json:"buyer_id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	ItemType     string             `json:"item_type"`
	Quantity     int32              `json:"quantity"`
	PricePerUnit pgtype.Numeric     `json:"price_per_unit"`
	TradedAt     pgtype.Timestamptz `json:"traded_at"`
}

type Player struct {
	ID           uuid.UUID          `json:"id"`
	DiscordID    string             `json:"discord_id"`
	Username     string             `json:"username"`
	DisplayColor string             `json:"display_color"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	IsDeleted    bool               `json:"is_deleted"`
}

type Property struct {
	ID               uuid.UUID          `json:"id"`
	XCoord           int32              `json:"x_coord"`
	YCoord           int32              `json:"y_coord"`
	ZoneType         string             `json:"zone_type"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	DevelopmentLevel int32              `json:"development_level"`
	AssessedValue    pgtype.Numeric     `json:"assessed_value"`
	LastTaxPaidAt    pgtype.Timestamptz `json:"last_tax_paid_at"`
}

type Transaction struct {
	ID              uuid.UUID          `json:"id"`
	AccountID       uuid.UUID          `json:"account_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	EntryType       EntryType          `json:"entry_type"`
	TransactionType TransactionType    `json:"transaction_type"`
	ReferenceID     pgtype.UUID        `json:"reference_id"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
