// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (discord_id, username, display_color)
VALUES ($1, $2, $3)
RETURNING id, discord_id, username, display_color, registered_at, last_active_at, is_deleted
`

type CreatePlayerParams struct {
	DiscordID    string `json:"discord_id"`
	Username     string `json:"username"`
	DisplayColor string `json:"display_color"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.DiscordID, arg.Username, arg.DisplayColor)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.DisplayColor,
		&i.RegisteredAt,
		&i.LastActiveAt,
		&i.IsDeleted,
	)
	return i, err
}

const getPlayerByDiscordID = `-- name: GetPlayerByDiscordID :one
SELECT id, discord_id, username, display_color, registered_at, last_active_at, is_deleted FROM players
WHERE discord_id = $1 AND is_deleted = false
`

func (q *Queries) GetPlayerByDiscordID(ctx context.Context, discordID string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByDiscordID, discordID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.DisplayColor,
		&i.RegisteredAt,
		&i.LastActiveAt,
		&i.IsDeleted,
	)
	return i, err
}

const softDeletePlayer = `-- name: SoftDeletePlayer :exec
UPDATE players SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeletePlayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePlayer, id)
	return err
}

const updateLastActive = `-- name: UpdateLastActive :exec
UPDATE players SET last_active_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastActive, id)
	return err
}
