// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: property.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (x_coord, y_coord, zone_type, assessed_value)
VALUES ($1, $2, $3, $4)
RETURNING id, x_coord, y_coord, zone_type, owner_id, development_level, assessed_value, last_tax_paid_at
`

type CreatePropertyParams struct {
	XCoord        int32          `json:"x_coord"`
	YCoord        int32          `json:"y_coord"`
	ZoneType      string         `json:"zone_type"`
	AssessedValue pgtype.Numeric `json:"assessed_value"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.XCoord,
		arg.YCoord,
		arg.ZoneType,
		arg.AssessedValue,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.XCoord,
		&i.YCoord,
		&i.ZoneType,
		&i.OwnerID,
		&i.DevelopmentLevel,
		&i.AssessedValue,
		&i.LastTaxPaidAt,
	)
	return i, err
}

const getPropertyByCoords = `-- name: GetPropertyByCoords :one
SELECT id, x_coord, y_coord, zone_type, owner_id, development_level, assessed_value, last_tax_paid_at FROM properties
WHERE x_coord = $1 AND y_coord = $2
`

type GetPropertyByCoordsParams struct {
	XCoord int32 `json:"x_coord"`
	YCoord int32 `json:"y_coord"`
}

func (q *Queries) GetPropertyByCoords(ctx context.Context, arg GetPropertyByCoordsParams) (Property, error) {
	row := q.db.QueryRow(ctx, getPropertyByCoords, arg.XCoord, arg.YCoord)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.XCoord,
		&i.YCoord,
		&i.ZoneType,
		&i.OwnerID,
		&i.DevelopmentLevel,
		&i.AssessedValue,
		&i.LastTaxPaidAt,
	)
	return i, err
}

const recordTaxPayment = `-- name: RecordTaxPayment :exec
UPDATE properties SET last_tax_paid_at = NOW()
WHERE id = $1
`

func (q *Queries) RecordTaxPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordTaxPayment, id)
	return err
}

const updateAssessedValue = `-- name: UpdateAssessedValue :exec
UPDATE properties SET assessed_value = $1
WHERE id = $2
`

type UpdateAssessedValueParams struct {
	AssessedValue pgtype.Numeric `json:"assessed_value"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAssessedValue(ctx context.Context, arg UpdateAssessedValueParams) error {
	_, err := q.db.Exec(ctx, updateAssessedValue, arg.AssessedValue, arg.ID)
	return err
}

const updatePropertyOwner = `-- name: UpdatePropertyOwner :exec
UPDATE properties SET owner_id = $1
WHERE id = $2
`

type UpdatePropertyOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePropertyOwner(ctx context.Context, arg UpdatePropertyOwnerParams) error {
	_, err := q.db.Exec(ctx, updatePropertyOwner, arg.OwnerID, arg.ID)
	return err
}
