// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAnomalyFlag(ctx context.Context, arg CreateAnomalyFlagParams) (AnomalyFlag, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateEmployment(ctx context.Context, arg CreateEmploymentParams) (Employment, error)
	CreateListing(ctx context.Context, arg CreateListingParams) (MarketListing, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	DecrementListingQuantity(ctx context.Context, arg DecrementListingQuantityParams) error
	GetAccountBalance(ctx context.Context, accountID uuid.UUID) (int32, error)
	GetAccountsByPlayer(ctx context.Context, playerID pgtype.UUID) ([]Account, error)
	GetActiveListingsByItem(ctx context.Context, arg GetActiveListingsByItemParams) ([]MarketListing, error)
	GetBusinessesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Business, error)
	GetDailyLaborByDay(ctx context.Context, economicDay int32) ([]DailyLabor, error)
	GetOpenAnomalies(ctx context.Context) ([]AnomalyFlag, error)
	GetPlayerByDiscordID(ctx context.Context, discordID string) (Player, error)
	GetPropertyByCoords(ctx context.Context, arg GetPropertyByCoordsParams) (Property, error)
	GetRecentTradesByItem(ctx context.Context, arg GetRecentTradesByItemParams) ([]MarketTrade, error)
	GetTransactionHistory(ctx context.Context, arg GetTransactionHistoryParams) ([]Transaction, error)
	GetTreasuryAccount(ctx context.Context) (Account, error)
	LogAdminAction(ctx context.Context, arg LogAdminActionParams) (AdminAuditLog, error)
	PostTransaction(ctx context.Context, arg PostTransactionParams) (Transaction, error)
	RecordEconomicSnapshot(ctx context.Context, arg RecordEconomicSnapshotParams) (EconomicSnapshot, error)
	RecordTaxPayment(ctx context.Context, id uuid.UUID) error
	RecordTrade(ctx context.Context, arg RecordTradeParams) (MarketTrade, error)
	SoftDeletePlayer(ctx context.Context, id uuid.UUID) error
	TerminateEmployment(ctx context.Context, id uuid.UUID) error
	UpdateAnomalyStatus(ctx context.Context, arg UpdateAnomalyStatusParams) error
	UpdateAssessedValue(ctx context.Context, arg UpdateAssessedValueParams) error
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error
	UpdateLastActive(ctx context.Context, id uuid.UUID) error
	UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) error
	UpdateProductionConfig(ctx context.Context, arg UpdateProductionConfigParams) error
	UpdatePropertyOwner(ctx context.Context, arg UpdatePropertyOwnerParams) error
	UpsertDailyLabor(ctx context.Context, arg UpsertDailyLaborParams) (DailyLabor, error)
}

var _ Querier = (*Queries)(nil)
