// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnomalyFlag = `-- name: CreateAnomalyFlag :one
INSERT INTO anomaly_flags (flag_type, implicated_player_ids, evidence_summary)
VALUES ($1, $2, $3)
RETURNING id, flag_type, implicated_player_ids, evidence_summary, detected_at, review_status
`

type CreateAnomalyFlagParams struct {
	FlagType            string      `json:"flag_type"`
	ImplicatedPlayerIds []uuid.UUID `json:"implicated_player_ids"`
	EvidenceSummary     pgtype.Text `json:"evidence_summary"`
}

func (q *Queries) CreateAnomalyFlag(ctx context.Context, arg CreateAnomalyFlagParams) (AnomalyFlag, error) {
	row := q.db.QueryRow(ctx, createAnomalyFlag, arg.FlagType, arg.ImplicatedPlayerIds, arg.EvidenceSummary)
	var i AnomalyFlag
	err := row.Scan(
		&i.ID,
		&i.FlagType,
		&i.ImplicatedPlayerIds,
		&i.EvidenceSummary,
		&i.DetectedAt,
		&i.ReviewStatus,
	)
	return i, err
}

const getOpenAnomalies = `-- name: GetOpenAnomalies :many
SELECT id, flag_type, implicated_player_ids, evidence_summary, detected_at, review_status FROM anomaly_flags
WHERE review_status = 'OPEN'
ORDER BY detected_at DESC
`

func (q *Queries) GetOpenAnomalies(ctx context.Context) ([]AnomalyFlag, error) {
	rows, err := q.db.Query(ctx, getOpenAnomalies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnomalyFlag{}
	for rows.Next() {
		var i AnomalyFlag
		if err := rows.Scan(
			&i.ID,
			&i.FlagType,
			&i.ImplicatedPlayerIds,
			&i.EvidenceSummary,
			&i.DetectedAt,
			&i.ReviewStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAdminAction = `-- name: LogAdminAction :one
INSERT INTO admin_audit_log (admin_player_id, target_player_id, action_type, parameters)
VALUES ($1, $2, $3, $4)
RETURNING id, admin_player_id, target_player_id, action_type, parameters, executed_at
`

type LogAdminActionParams struct {
	AdminPlayerID  uuid.UUID   `json:"admin_player_id"`
	TargetPlayerID pgtype.UUID `json:"target_player_id"`
	ActionType     string      `json:"action_type"`
	Parameters     []byte      `json:"parameters"`
}

func (q *Queries) LogAdminAction(ctx context.Context, arg LogAdminActionParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, logAdminAction,
		arg.AdminPlayerID,
		arg.TargetPlayerID,
		arg.ActionType,
		arg.Parameters,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminPlayerID,
		&i.TargetPlayerID,
		&i.ActionType,
		&i.Parameters,
		&i.ExecutedAt,
	)
	return i, err
}

const recordEconomicSnapshot = `-- name: RecordEconomicSnapshot :one
INSERT INTO economic_snapshots (economic_day, metrics)
VALUES ($1, $2)
RETURNING id, economic_day, metrics, created_at
`

type RecordEconomicSnapshotParams struct {
	EconomicDay int32  `json:"economic_day"`
	Metrics     []byte `json:"metrics"`
}

func (q *Queries) RecordEconomicSnapshot(ctx context.Context, arg RecordEconomicSnapshotParams) (EconomicSnapshot, error) {
	row := q.db.QueryRow(ctx, recordEconomicSnapshot, arg.EconomicDay, arg.Metrics)
	var i EconomicSnapshot
	err := row.Scan(
		&i.ID,
		&i.EconomicDay,
		&i.Metrics,
		&i.CreatedAt,
	)
	return i, err
}

const updateAnomalyStatus = `-- name: UpdateAnomalyStatus :exec
UPDATE anomaly_flags SET review_status = $1
WHERE id = $2
`

type UpdateAnomalyStatusParams struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	ID           uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateAnomalyStatus(ctx context.Context, arg UpdateAnomalyStatusParams) error {
	_, err := q.db.Exec(ctx, updateAnomalyStatus, arg.ReviewStatus, arg.ID)
	return err
}
